package com.quora.service.models.response;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Schema(description = "User Details OutputDTO")
public class UserDetailsOutputDTO {
    @Schema(name = "userId", example = "1323232323239", description = "Unique userId of the user generated by system.")
    private UUID userId;
    @Schema(name = "username", example = "iamanand",description = "User name of the user.")
    private String username;
    @Schema(name = "emailId", example = "anyemail@xyz.com", description = "Email Id of the user.")
    private String emailId;
    @Schema(name = "bio", example = "My name is Anand.", description = "Bio of the user.")
    private String bio;
}
